#application.yml
spring:
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    enabled: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/file_serv
    username: postgres
    password: 123
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  minio:
    url: http://localhost:9000
    access-key: 12345678
    secret-key: 87654321
server:
  port: 8082

